# Generated by Django 4.1.5 on 2023-06-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.IntegerField(default=0)),
                ("discount", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("length", models.IntegerField(default=0)),
                ("thumbnail", models.ImageField(upload_to="files/thumbnail")),
                ("resources", models.FileField(upload_to="files/resources")),
            ],
        ),
    ]
