# Generated by Django 4.1.5 on 2023-06-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_video_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_author",
            field=models.CharField(default=0, max_length=100),
        ),
    ]
