# Generated by Django 4.1.5 on 2023-06-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_course_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
