# Generated by Django 4.1.5 on 2023-07-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_rename_prerequisites_prerequisite_usercourse_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="User",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.usercourse",
            ),
        ),
    ]
